# Generated by Django 4.2.5 on 2023-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='veiculos/')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto')], max_length=10)),
                ('cor', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado')], max_length=10)),
                ('km_rodados', models.PositiveIntegerField()),
                ('passagem_leilao', models.BooleanField(default=False)),
                ('formas_pagamento', models.CharField(choices=[('avista', 'À Vista'), ('parcelado', 'Parcelado')], max_length=10)),
            ],
        ),
    ]
